name: Generate Schematron Report
on: push

jobs:
  linux:
    name: Linux build on JDK ${{ matrix.jdk_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version: [1.8]

    steps:
    - name: Checkout
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675   # v2.3.3

    - name: Set up JDK
      uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2 # v1.4.3
      with:
        java-version: ${{ matrix.jdk_version }}

    - name: Build with Maven
      run: mvn dependency:go-offline --file ./java/pom.xml