name: Generate Schematron Report
on: push

jobs:
  linux:
    name: Generate Schematron report Linux with JDK ${{ matrix.jdk_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk_version: [1.8]
        schematron_version: [refs/tag/2020-10-01]

    steps:
    - name: Checkout
      uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675   # v2.3.3

    - name: Checkout Schematron Libraries
      uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e   # v.1.2.0
      with:
        repository: schematron/schematron
        ref: ${{ matrix.schematron_version }}

    - name: Set up JDK
      uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2 # v1.4.3
      with:
        java-version: ${{ matrix.jdk_version }}

    - name: Cache or Restore Maven Dependencies
      uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16      # v2.1.2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
         
    - name: Build with Maven
      run: mvn dependency:go-offline --file ./java/pom.xml